In [75]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import tensorflow as tf

In [76]:
# Defining our Sigmoid function
def sigmoid(Z):
    g = 1/(1+np.exp(-Z))
    return g

In [77]:
# Defining The Dense Layer
def Dense(a_in, W, b, g):
    units = W.shape[1]
    a_out = np.zeros(units)
    for i in range(units):
        w = W[:, i]
        z = np.dot(w, a_in)+b[i]
        a_out[i] = g(z)
    
    return a_out

In [111]:
# Defining the sequential for Dense Layers
def Sequential(a0, W1, b1, W2, b2):
    a1 = Dense(a0, W1, b1, sigmoid)
    a2 = Dense(a1, W2, b2, sigmoid)
    return a2

In [112]:
# make a prediction by running the model.
def predict(X, W1, b1, W2, b2):
    m = X.shape[0]
    p = np.zeros((m,1))
    for i in range(m):
        p[i,0] = Sequential(X[i], W1, b1, W2, b2)
    return(p)

In [113]:
# Defining W's and b's
W1_tmp = np.array( [[-8.93,  0.29, 12.9 ], [-0.1,  -7.32, 10.81]] )
b1_tmp = np.array( [-9.82, -9.28,  0.96] )
W2_tmp = np.array( [[-31.18], [-27.59], [-32.56]] )
b2_tmp = np.array( [15.41] )

In [114]:
# Training Set
def load_coffee_data():
    """ Creates a coffee roasting data set.
        roasting duration: 12-15 minutes is best
        temperature range: 175-260C is best
    """
    rng = np.random.default_rng(2)
    X = rng.random(400).reshape(-1,2)
    X[:,1] = X[:,1] * 4 + 11.5          # 12-15 min is best
    X[:,0] = X[:,0] * (285-150) + 150  # 350-500 F (175-260 C) is best
    Y = np.zeros(len(X))
    
    i=0
    for t,d in X:
        y = -3/(260-175)*t + 21
        if (t > 175 and t < 260 and d > 12 and d < 15 and d<=y ):
            Y[i] = 1
        else:
            Y[i] = 0
        i += 1

    return (X, Y.reshape(-1,1))

x_train, y_train = load_coffee_data()
print(f"x_shape={x_train.shape}, y_shape={y_train.shape}")
x_train

x_shape=(200, 2), y_shape=(200, 1)


array([[185.31763812,  12.69396457],
       [259.92047498,  11.86766377],
       [231.01357101,  14.41424211],
       [175.3666449 ,  11.72058651],
       [187.12086467,  14.12973206],
       [225.90586448,  12.10024905],
       [208.40515676,  14.17718919],
       [207.07593089,  14.0327376 ],
       [280.60385359,  14.23225929],
       [202.86935247,  12.24901028],
       [196.70468985,  13.54426389],
       [270.31327028,  14.60225577],
       [192.94979108,  15.19686759],
       [213.57283453,  14.27503537],
       [164.47298664,  11.91817423],
       [177.25750542,  15.03779869],
       [241.7745473 ,  14.89694529],
       [236.99889634,  13.12616959],
       [219.73805621,  13.87377407],
       [266.38592796,  13.25274466],
       [270.45241485,  13.95486775],
       [261.96307698,  13.49222422],
       [243.4899478 ,  12.8561015 ],
       [220.58184803,  12.36489356],
       [163.59498627,  11.65441652],
       [244.76317931,  13.32572248],
       [271.19410986,  14.84073282],
 

In [115]:
# Normalising The Data
normal_l = tf.keras.layers.Normalization()
normal_l.adapt(x_train)
xn_train = normal_l(x_train)
xn_train

<tf.Tensor: shape=(200, 2), dtype=float32, numpy=
array([[-0.8345551 , -0.6528792 ],
       [ 1.0323051 , -1.3851453 ],
       [ 0.3089391 ,  0.8716251 ],
       [-1.0835688 , -1.5154841 ],
       [-0.7894313 ,  0.6194935 ],
       [ 0.18112417, -1.1790283 ],
       [-0.25681356,  0.6615495 ],
       [-0.29007602,  0.5335373 ],
       [ 1.5498857 ,  0.7103532 ],
       [-0.39534125, -1.047197  ],
       [-0.54960555,  0.1006532 ],
       [ 1.2923743 ,  1.0382426 ],
       [-0.6435681 ,  1.5651861 ],
       [-0.12749763,  0.7482604 ],
       [-1.3561714 , -1.340383  ],
       [-1.0362518 ,  1.4242196 ],
       [ 0.57822186,  1.2993953 ],
       [ 0.45871606, -0.26986104],
       [ 0.02678081,  0.3926646 ],
       [ 1.1940966 , -0.15769024],
       [ 1.2958566 ,  0.46452886],
       [ 1.0834192 ,  0.05453626],
       [ 0.6211478 , -0.5091947 ],
       [ 0.04789595, -0.94450104],
       [-1.3781425 , -1.5741245 ],
       [ 0.65300936, -0.09301733],
       [ 1.3144168 ,  1.24958   ],
     

In [120]:
predictions = predict(xn_train, W1_tmp, b1_tmp, W2_tmp, b2_tmp)
predictions

array([[9.99995609e-01],
       [7.42325959e-08],
       [3.56297639e-08],
       [1.26074143e-10],
       [9.99987214e-01],
       [9.96358413e-01],
       [4.57741264e-08],
       [1.66897066e-07],
       [3.56319798e-08],
       [9.99986164e-01],
       [9.99999686e-01],
       [3.56327056e-08],
       [2.28293154e-08],
       [3.61673812e-08],
       [7.03867494e-13],
       [5.79394502e-12],
       [3.56324617e-08],
       [6.41357601e-08],
       [4.03624456e-08],
       [3.52246083e-08],
       [3.56283183e-08],
       [3.55488627e-08],
       [8.39214170e-08],
       [9.99997753e-01],
       [5.07489617e-17],
       [3.56803013e-08],
       [3.56327582e-08],
       [3.35890338e-08],
       [3.56285251e-08],
       [9.99993340e-01],
       [5.09416155e-04],
       [2.29624370e-01],
       [1.76882094e-07],
       [1.38654118e-06],
       [4.14051466e-08],
       [3.55737238e-08],
       [3.56223512e-08],
       [3.71703825e-08],
       [2.21474442e-09],
       [3.56264880e-08],


In [121]:
yhat = np.zeros_like(predictions)
for i in range(len(predictions)):
    if predictions[i] > 0.5:
        yhat[i] = 1
    else:
        yhat[i] = 0

print(yhat)

[[1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.