<h1 style="color: Red"> Numpy For Data Science </h1>

In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3, 4])

In [3]:
arr # printing the array

array([1, 2, 3, 4])

In [4]:
arr.shape # no. of rows and columns

(4,)

In [5]:
arr = np.array([[1, 2],
                [4, 5], 
                [7, 8]])
arr.shape # no. of rows and cols: (3, 2)
arr.ndim # dimenstion of the array: 2
arr.itemsize # To see the size of each element in the array: 4(int)
arr.dtype # To see the data type of the array: dtype('int32')
arr.size # returns the total no of elements: 6
arr.min() # used to search the minimum value: 1
arr.max() # used to search the maximum value: 8
arr.sum() # used to sum the all values: 27
arr.sum(axis=0) # used to sum the y-axis values: array([12, 15])
arr.sum(axis=1) # used to sum the x-axis values: array([3, 9, 15])
np.sqrt(arr) # returns an array with all the values of sqrt
arr # printing the array

array([[1, 2],
       [4, 5],
       [7, 8]])

In [6]:
arr = np.array([[1, 2], [3, 4], [5, 6]], dtype=complex) # creating a complex type array
arr

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]])

In [7]:
arr = np.zeros((2, 4)) # array with containing 0's only
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
arr = np.ones((2, 3)) # array with containing 1's only 
arr

array([[1., 1., 1.],
       [1., 1., 1.]])

In [9]:
arr = np.arange(1, 5, 1) # array with a range of numbers thirst parameter is a step
arr

array([1, 2, 3, 4])

In [10]:
arr = np.linspace(1, 5, 10) # A array with 1 to 5 numbers where is 10 step gap between them
arr

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [11]:
arr = np.array([[1, 2],
                [3, 4],
                [5, 6]])
arr.reshape(2, 3) # used to reshape the array: (3, 2) to (2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
arr = np.array([[1, 2],
                [3, 4],
                [5, 6]])
arr.ravel() # used to change the array dimenstion to 1-d array

array([1, 2, 3, 4, 5, 6])

In [13]:
arr1 = np.array([[1, 2],
                [3, 4]])

arr2 = np.array([[4, 9],
                [7, 6]])

arr1+arr2 # return an array by adding arr1 and arr2
arr1-arr2 # return an array by subtracting arr2 from arr1
arr1*arr2 # return an array by multipying the values of arr1 by arr2
arr1/arr2 # return an array by dividing the all values of arr1 by arr2
arr1.dot(arr2) # return a matrix multiplication array

array([[18, 21],
       [40, 51]])